In [21]:
import numpy as np

def echelon(matrice):
  
    pivot_position = 0
    
    for row_number in range(matrice.shape[0]):
      
        temp = row_number
        
        while matrice[temp, pivot_position] == 0:
            temp += 1
            if matrice.shape[0] == temp:
                temp = row_number
                pivot_position += 1
                if matrice.shape[0] == pivot_position:
                    return False
                  
        matrice[[temp, row_number]] = matrice[[row_number, temp]]
        
        if matrice[row_number, pivot_position] != 0:
            matrice[row_number] = matrice[row_number] / matrice[row_number, pivot_position]
            
        for i in range(matrice.shape[0]):
            if i != row_number:
                matrice[i] = matrice[i] - (matrice[row_number] * matrice[i, pivot_position])
                
        pivot_position += 1
        
        print("step " + str(row_number + 1) + ": ")
        print(matrice)
        
    return True

  
n = int(input("enter n: "))
A = np.empty((0, n))

for i in range(n):
  A = np.vstack((A, list(input("enter row " + str(i + 1) + " of A: ").split())))

b = np.empty((0, 1))
for i in range(n):
  b = np.vstack((b, list(input("enter row " + str(i + 1) + " of b: ").split())))


augmented_matrice = np.column_stack((A, b))
augmented_matrice = augmented_matrice.astype(np.float)

print("This is A|b:")
print(augmented_matrice)

if echelon(np.column_stack((A, b)).astype(np.float)):
    print("This is final answer of A|b:")
    print(np.linalg.solve(A.astype(np.float), b.astype(np.float)))

print("This is upper triangular of A|b:")
upper_triangular = np.triu(augmented_matrice)
print(upper_triangular)

enter n: 5
enter row 1 of A: 1 3 2 -4 3
enter row 2 of A: -2 -1 2 6 4
enter row 3 of A: 0 -1 3 -5 1
enter row 4 of A: 3 -4 2 5 -7
enter row 5 of A: 1 2 -8 6 1
enter row 1 of b: -3
enter row 2 of b: 19
enter row 3 of b: -2
enter row 4 of b: -11
enter row 5 of b: 4
This is A|b:
[[  1.   3.   2.  -4.   3.  -3.]
 [ -2.  -1.   2.   6.   4.  19.]
 [  0.  -1.   3.  -5.   1.  -2.]
 [  3.  -4.   2.   5.  -7. -11.]
 [  1.   2.  -8.   6.   1.   4.]]
step 1: 
[[  1.   3.   2.  -4.   3.  -3.]
 [  0.   5.   6.  -2.  10.  13.]
 [  0.  -1.   3.  -5.   1.  -2.]
 [  0. -13.  -4.  17. -16.  -2.]
 [  0.  -1. -10.  10.  -2.   7.]]
step 2: 
[[  1.    0.   -1.6  -2.8  -3.  -10.8]
 [  0.    1.    1.2  -0.4   2.    2.6]
 [  0.    0.    4.2  -5.4   3.    0.6]
 [  0.    0.   11.6  11.8  10.   31.8]
 [  0.    0.   -8.8   9.6   0.    9.6]]
step 3: 
[[  1.           0.           0.          -4.85714286  -1.85714286
  -10.57142857]
 [  0.           1.           0.           1.14285714   1.14285714
    2.42857143]
 [